config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path_prefix => 'd'
  resources :users
  resources :cars do
    resources :bookings
  end

  root 'users#index'

  get '/secret', to: 'users#secret', as: :secret
  get '/car_history', to: 'cars#bookings', via: 'get'
  match '/show_all',   to: 'users#show_all', via: 'get'
  get '/search', to: 'cars#search', via: 'get'
  get '/users/:id/bookings', to: 'users#booking', as: :user_bookings
  get '/bookings/:id/check_out', to: 'bookings#check_out', as: :check_out
  get '/bookings/:id/return', to: 'bookings#return', as: :return
  get '/bookings/:id/cancel', to: 'bookings#cancel', as: :cancel_booking

=begin
  get 'bookings/new'

  get 'bookings/create'

  get 'bookings/update'

  get 'bookings/edit'

  get 'bookings/destroy'

  get 'bookings/index'

  get 'bookings/show'

  get 'cars/new'

  get 'cars/create'

  get 'cars/update'

  get 'cars/edit'

  get 'cars/destroy'

  get 'cars/index'

  get 'cars/show'

  get 'users/new'

  get 'users/create'

  get 'users/update'

  get 'users/edit'

  get 'users/destroy'

  get 'users/index'

  get 'users/show'
=end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  has_many :bookings

  enum role: [:user, :admin, :superadmin]
  after_initialize :set_default_role, :if => :new_record?


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, :presence => true

  def set_default_role
    self.role ||= :user if self.role.nil?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: []
  before_action :authorize_admin, only: [:new, :create, :destroy, :show_all, :edit, :show, :update]

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def edit
    @user = User.find(params[:id])
    @role = params[:role]
  end

  def show_all
    @role = params[:role]
    @users = User.where(:role => User.roles[@role.to_sym]).where.not(id: current_user.id).all

    respond_to do |format|
      format.html # index.html.erb
      format.json {render json: @users}
    end
  end

  def show
    @bookings = Booking.where(:user_id => (params[:id])).all.sort_by &:created_at
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json {render json: @bookings}
    end
  end

  def index
    if !current_user.try(:user?) then
      @bookings = Booking.joins(:car).joins(:user).all.order(:created_at).reverse_order
    end
  end

  def update
    @user = User.find(params[:id])
    @role = params[:role]

    respond_to do |format|
      if @user.update_attributes(user_params) then
        flash[:notice] = "#{@role.capitalize} #{@user.name.capitalize} was successfully updated."
        format.html {redirect_to action: "show_all", role: @role}
      else
        flash[:notice] = "Please verify the details"
        format.html {render action: "edit"}
        format.json {render json: @user.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @role = params[:role]

    return if(@role.equal?"superadmin")

    if Booking.where("user_id = ? AND status != 3", @user.id).to_a().length > 0 then
      flash[:notice] = "User #{@user.name.capitalize} holds a car. Please manage booking before deleting this User"
    else
      @user.destroy
      flash[:notice] = "#{@role.capitalize} #{@user.name.capitalize} was successfully deleted."
    end

    respond_to do |format|
      format.html {redirect_to action: "show_all", role: @role}
      format.json {head :no_content}
    end
  end

  def new
    @user = User.new
    @role = params[:role]
    respond_to do |format|
      format.html # new.html.erb
      format.json {render json: @user}
    end
  end

  def booking
    @user = User.where(:id => params[:id]).last
    @bookings = Booking.where(:user_id => params[:id]).joins(:car).order(:created_at).reverse_order.to_a()
  end

  # POST /user
  # POST /user.json
  def create
    @user = User.new(user_params)
    @role = params[:role]

    authorize_superadmin if(@role.equal?"superadmin")

    @user.role = User.roles[@role.to_sym]
    respond_to do |format|
      if @user.save
        flash[:notice] = "#{@role.capitalize} #{@user.name.capitalize} was successfully created."
        format.html {redirect_to action: "show_all", role: @role}
      else
        flash[:notice] = "Please verify the details"
        format.html {render action: "new"}
        format.json {render json: @user.errors, status: :unprocessable_entity}
      end
    end
  end

  def authorize_admin
    return unless !current_user.try(:admin?) and !current_user.try(:superadmin?)
    redirect_to root_path, alert: 'Admins only!'
  end

  def authorize_superadmin
    return unless !current_user.try(:superadmin?)
    redirect_to root_path, alert: 'Super Admins only!'
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_admin_menu.html.erb
<% if user_signed_in? %>
    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          Manage
          <span class="caret"></span>
        </a>
        <% if current_user.try(:admin?) or current_user.try(:superadmin?)   %>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Users', show_all_path(:role => "user"), method: :get %></li>
              <li><%= link_to 'Admins', show_all_path(:role => "admin"), method: :get %></li>
              <% if current_user.try(:superadmin?)   %>
                  <li><%= link_to 'Super Admins', show_all_path(:role => "superadmin"), method: :get %></li>
              <% end %>
              <li><%= link_to 'Cars', cars_path %></li>
            </ul>
      <% elsif current_user.try(:user?)  %>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Bookings', user_bookings_url(current_user.id) %></li>
            </ul>
      <% end %>

      </li>
</ul>
<% end %>

app/views/users/booking.html.erb
<h3 class="text-center">Booking History of <%= @user.name.capitalize  %> </h3>
<table class="table">
  <tr>
    <th>Model</th>
    <th>Manufacturer</th>
    <th>Rate</th>
    <th>Action</th>
    <th>
  </tr>
  <% @bookings.each do |book| %>
    <tr>
      <td><%= book.car.model %></td>
      <td><%= book.car.manufacturer %></td>
      <td><%= book.car.rate %></td>
      <td>
        <% if book.status == "reserved" %>
          <%= link_to "Check Out", check_out_url(book.id) %>
        <% elsif book.status == "checkedOut" %>
          <%= link_to "Return", return_url(book.id) %>
        <% else %>
          Returned
        <% end %>
        <% if book.status != "returned" %>
          /<%= link_to "Cancel", cancel_booking_url(book.id), data: { confirm: "Are you sure?" } %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<%= link_to "Back", :back, class: 'btn btn-default btn-sm' %>

app/views/users/edit.html.erb
<% header "Edit #{@user.name.to_s.humanize}" %>

<%= form_for(@user, url: user_path(:role=>@role), html: { method: :put }) do |f| %>
    <%= devise_error_messages! %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>

    <%= f.submit "Update", class: 'btn btn-primary' %>
<% end %>

<%= link_to "Back", :back, class: 'btn btn-default btn-sm' %>

app/views/users/index.html.erb
<% content_for :top_content do %>
    <div class="jumbotron">
      <div class="container">
        <% if user_signed_in? %>
            <h3 class="text-center">Welcome <%= current_user.name %></h3>
            <br />
            <h4 class="text-center">Manage All Bookings</h4>
            <br />
            <% if current_user.try(:user?) %>
                <p>
                  <%= link_to 'Rent a Car', cars_path, class: 'btn btn-primary btn-lg' %>
                </p>
            <% else %>
                <table class="table">
                  <tr>
                    <th>Model</th>
                    <th>Manufacturer</th>
                    <th>User</th>
                    <th>Status</th>
                    <th>Actions</th>
                  </tr>
                  <% @bookings.each do |book| %>
                    <tr>
                      <td><%= book.car.model %></td>
                      <td><%= book.car.manufacturer %></td>
                      <td><%= book.user.name %></td>
                      <td style="text-transform: capitalize"><%= book.status %></td>
                      <td>
                        <% if book.status == "reserved" %>
                          <%= link_to "Cancel/", cancel_booking_url(book.id), data: { confirm: "Are you sure? "} %>
                          <%= link_to "Check Out", check_out_url(book.id) %>
                        <% elsif book.status == "returned" %>
                          None
                        <% elsif book.status == "checkOut" %>
                          <%= link_to "Return", return_url(book.id) %>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                </table>
            <% end %>
        <% else %>
            <h1>Welcome to Escelera!</h1>
            <p>Register to get started.</p>
            <p>
              <%= link_to 'Register', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
            </p>
        <% end %>
      </div>
    </div>
<% end %>

app/views/users/new.html.erb
<% header "New  #{@role.capitalize}" %>

<%= form_for(@user, url: users_path(:role=>@role), html: { method: :post })  do |f| %>
    <%= devise_error_messages! %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
      <% if @validatable %>
          <span class="help-block"><%= @minimum_password_length %> characters minimum</span>
      <% end %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control' %>
    </div>
    <%= link_to "Back", :back, class: 'btn btn-primary' %>
    <%= f.submit "Create", class: 'btn btn-primary' %>
<% end %>

app/views/users/secret.html.erb
<% header "Secret!" %>

app/views/users/show.html.erb
Show#User details
+ include user bookings

app/views/users/show_all.html.erb
<% content_for :top_content do %>
    <div class="jumbotron">
      <div class="container">
        <h2>Listing <%= @role.capitalize + 's' %></h2>
        <%= devise_error_messages! %>
        <table class="table">
          <tr>
            <th>Name</th>
            <th>Email</th>
            <% if @role == 'user' %>
                <th>History</th>
            <% end %>
            <th></th>
            <th></th>
          </tr>

          <% if !@users.nil? then
               @users.each do |user| %>
                  <tr>
                    <td><%= user.name %></td>
                    <td><%= user.email %></td>
                    <% if @role == 'user' %>
                        <td><%= link_to 'Show', user_bookings_url(user.id) %></td>
                        <td><%= link_to 'Edit', edit_user_path(user, :role => @role) %></td>
                    <% end %>
                    <% if @role != 'superadmin' %>
                        <td><%= link_to 'Delete', user_path(user, :role => @role), method: :delete, data: {confirm: 'Are you sure?'} %></td>
                    <% end %>
                  </tr>
              <% end %>
          <% end %>
        </table>
        <%= link_to "Back", :back, class: 'btn btn-default btn-sm' %>
        <% if @role != 'user' %>
            <%= link_to "Create New", new_user_path(:role => @role), class: 'btn btn-default btn-sm' %>
        <% end %>
      </div>
    </div>
<% end %>