config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path_prefix => 'd'
  resources :users
  resources :cars do
    resources :bookings
  end

  root 'users#index'

  get '/secret', to: 'users#secret', as: :secret
  get '/car_history', to: 'cars#bookings', via: 'get'
  match '/show_all',   to: 'users#show_all', via: 'get'
  get '/search', to: 'cars#search', via: 'get'
  get '/users/:id/bookings', to: 'users#booking', as: :user_bookings
  get '/bookings/:id/check_out', to: 'bookings#check_out', as: :check_out
  get '/bookings/:id/return', to: 'bookings#return', as: :return
  get '/bookings/:id/cancel', to: 'bookings#cancel', as: :cancel_booking

=begin
  get 'bookings/new'

  get 'bookings/create'

  get 'bookings/update'

  get 'bookings/edit'

  get 'bookings/destroy'

  get 'bookings/index'

  get 'bookings/show'

  get 'cars/new'

  get 'cars/create'

  get 'cars/update'

  get 'cars/edit'

  get 'cars/destroy'

  get 'cars/index'

  get 'cars/show'

  get 'users/new'

  get 'users/create'

  get 'users/update'

  get 'users/edit'

  get 'users/destroy'

  get 'users/index'

  get 'users/show'
=end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :bookings
  attr_accessor :status

  validates :model, :presence => true
  validates :manufacturer, :presence => true
  validates :number, :presence => true, :uniqueness => true
  validates :rate, :presence => true
  validates :style, :presence => true, :inclusion => { :in => ["Hatchback", "Sedan", "SUV"] }
  validates :location, :presence => true

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authorize_user, only: [:index, :show]
  before_action :authorize_admin, only: [:new, :create, :destroy, :edit, :update]
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html {redirect_to cars_path, notice: 'Car was successfully created.'}
        format.json {render action: 'show', status: :created, location: @car}
      else
        format.html {render action: 'new'}
        format.json {render json: @car.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    @car = Car.find(params[:id])
    if Booking.where("car_id = ? AND status == 2", @car.id).to_a().length > 0 then
      flash[:notice] = "Car Number: #{@car.number.capitalize} is already checkedout. Please manage booking before updating this Car"
    else
      if @car.update_attributes(car_params)
        format.html { redirect_to cars_path, notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
    respond_to do |format|
        format.html { redirect_to cars_path}
        format.json { head :no_content }
      end
    end

  def edit
    @car = Car.find(params[:id])
  end

  def destroy
    if Booking.where("car_id = ? AND status == 1 OR status == 2", @car.id).to_a().length > 0 then
      flash[:notice] = "Car Number: #{@car.number.capitalize} have pending bookings. Please manage booking before deleting this Car"
    else
      @car.destroy
      flash[:notice] = "Car Number: #{@car.number.capitalize} was successfully deleted."
    end
    respond_to do |format|
      format.html {redirect_to cars_url}
      format.json {head :no_content}
    end
  end

  def index
    @search = Car.search(params[:q])
    @cars = @search.result
    if (current_user.try(:user?))
      @booking = Booking.where(:user_id => current_user.id).where.not(status: 3).to_a()
    else
      @booking = []
    end

    if @booking.length <= 0 then
      @cars.each do |car|
        car.status = car_status car
      end
    else
      @cars = []
    end
    @cars
  end

  def show
  end

  def search
    @search = Car.search(params[:q])
    @cars = @search.result
  end

  def bookings
    @bookings = Booking.where(:car_id => params[:car_id])
  end

  def authorize_user
    return unless !user_signed_in?
    redirect_to root_path, alert: 'Please login first!'
  end

  def authorize_admin
    return unless !current_user.try(:admin?) and !current_user.try(:superadmin?)
    redirect_to root_path, alert: 'This page is for Admin or Super Admin only!'
  end

  private

    def set_car
      @car = Car.find(params[:id])
    end

  def car_params
    params.require(:car).permit(:model, :manufacturer, :number,
                                :rate, :style, :location)
  end

  def car_status car
    @booking = Booking.where("car_id = ? AND pickup_time <= ? AND return_time >=  ?", car.id, DateTime.now.to_s(:db), DateTime.now.to_s(:db))
    status = "Available"
    if @booking.exists?
      booking = @booking.last
      user = User.find(booking["user_id"])
      status = booking["status"].capitalize + " by " + view_context.link_to(user.name, user_bookings_url(user.id))
    end
    status
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
    <% if @car.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

          <ul>
            <% @car.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :model %><br>
      <%= f.text_field :model, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :manufacturer %><br>
      <%= f.text_field :manufacturer, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :number %><br>
      <%= f.text_field :number, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :rate %><br>
      <%= f.text_field :rate, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :style %><br>
      <%= f.select(:style, ['Hatchback', 'Sedan', 'SUV'], {}, {class: 'form-control'}) %>
    </div>
    <div class="form-group">
      <%= f.label :location %><br>
      <%= f.text_field :location, class: 'form-control' %>
    </div>
    <br>
    <div class="actions">
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to "Back", :back, class: 'btn btn-primary' %>
    </div>

<% end %>

app/views/cars/_search.html.erb
<%= search_form_for(@search, html: { class: :'form-inline' }) do |f| %>
    <div class="form-group">
      <%= f.label :model_cont, "Model" %>
      <%= f.text_field :model_cont,class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :manufacturer_cont, "Manufacturer" %>
      <%= f.text_field :manufacturer_cont, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :style_cont, "Style" %>
      <%= f.text_field :style_cont, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :location_cont, "Location" %>
      <%= f.text_field :location_cont, class: 'form-control' %>
    </div><br><br>
    <div class="actions"><%= f.submit "Search", class: 'btn btn-primary' %>
      <% if !current_user.try(:user?)  %>
          <%= link_to 'Add Car', new_car_path, class: 'btn btn-primary' %>
      <% end %>
    </div>

<% end %>

app/views/cars/_update_status.html.erb
<%= form_for [@car, @booking] do |f| %>
    <% if @booking.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

          <ul>
            <% @booking.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <h2> Please enter the details of user for whom car need to be reserved</h2>
    <div class='field'>
      <%= f.label :pickup_time %><br>
      <div class='input-group date' id='datetimepicker1'>
        <%= f.text_field :pickup_time, id: 'datetimepicker1', class: "form-control" %>
        <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
      </span>
      </div>
    </div>
    <br/>
    <div class='field'>
      <%= f.label :return_time %><br>
      <div class='input-group date' id='datetimepicker2'>
        <%= f.text_field :return_time, id: 'datetimepicker2', class: "form-control" %>
        <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
      </span>
      </div>
    </div>
    <br/>
    <div class='field'>
    <%= label_tag :select_user  %>
    <%= select_tag 'select_user', options_for_select(@users.collect{ |u| [u.name + "  :  " + u.email, u.id] }),class: "form-control" %>
    </div>

<% end %>

<script type="text/javascript">
    $(function () {
        $('#datetimepicker1').datetimepicker();
        $('#datetimepicker2').datetimepicker();
    });
</script>

app/views/cars/bookings.html.erb
<% content_for :top_content do %>
    <div class="jumbotron">
      <div class="container">
        <h2>Listing all bookings</h2>
        <%= devise_error_messages! %>
        <table class="table">
          <tr>
            <th>Booking ID</th>
            <th>UserID</th>
            <th>From</th>
            <th>To</th>
            <th>Status</th>
            <th>Action</th>
          </tr>

          <% if !@bookings.nil? then
               @bookings.each do |booking| %>
                  <tr>
                    <td><%= booking.id %></td>
                    <td><%= link_to booking.user_id, user_bookings_url(booking.user_id) %></td></td>
                    <td><%= booking.pickup_time.to_date %><br>
                      <%= booking.pickup_time.to_time.strftime("%I:%M %p")%></td>
                    <td><%= booking.return_time.to_date %><br>
                      <%= booking.return_time.to_time.strftime("%I:%M %p")%></td></td>
                    <td><%= booking.status.capitalize %></td>
                    <td>
                      <% if booking.status == "reserved" %>
                          <%= link_to "Check Out", check_out_url(booking.id) %>
                      <% elsif booking.status == "checkedOut" %>
                          <%= link_to "Return", return_url(booking.id) %>
                      <% else %>
                          Returned
                      <% end %>
                      <% if booking.status != "returned" %>
                          /<%= link_to "Cancel", cancel_booking_url(booking.id), data: { confirm: "Are you sure?" } %>
                      <% end %>
                  </tr>
              <% end %>
          <% end %>
        </table>
        <%= link_to "Back", :back, class: 'btn btn-default btn-sm' %>
      </div>
    </div>
<% end %>

app/views/cars/create.html.erb
<h1>Cars#create</h1>
<p>Find me in app/views/cars/create.html.erb</p>

app/views/cars/destroy.html.erb
<h1>Cars#destroy</h1>
<p>Find me in app/views/cars/destroy.html.erb</p>

app/views/cars/edit.html.erb
<% header "Edit car number #{@car.number}" %>
<%= render 'form' %>

app/views/cars/index.html.erb
<% if @booking.length > 0   %>
  <div class="jumbotron">
    <h4 class="text-center">It seems like you already have a car in the booking state.
    Please manage it before booking a new one</h4>
  </div>
<% else %>
  <h1>Listing Cars</h1>
    <%= render 'search' %><br><br>
  <table class="table">
    <tr>
      <th>Model</th>
      <th>Manufacturer</th>
      <th>Number</th>
      <th>Style</th>
      <th>Rate</th>
      <th>Location</th>
      <th>Action</th>
      <th>Current Status<br> (<%= Time.now.to_time.strftime("at %I:%M%p")%>)</th>
      <% if current_user.try(:admin?) or current_user.try(:superadmin?) %>
        <th></th>
        <th></th>
      <% end %>
    </tr>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.model %></td>
        <td><%= car.manufacturer %></td>
        <td><%= car.number %></td>
        <td><%= car.style %></td>
        <td><%= car.rate %></td>
        <td><%= car.location %></td>
        <td><%= link_to "Book", new_car_booking_path(car) %></td>
        <% if !current_user.try(:user?) %>
          <td><%= car.status.html_safe %> <br>
            <small><i><%= link_to "All Bookings", car_history_path(:car_id => car.id), method: :get %></i></small>
                <% end %>
        <% if (current_user.try(:admin?) or current_user.try(:superadmin?))%>   <!-- and car.status == "Available"   //need to confirm this-->
            <td><%= link_to "Edit", edit_car_path(car) %></td>
          <td><%= link_to "Delete", car, method: :delete, data: { confirm: "Are you sure?" } %></td>
        <% end %>
      </tr>
    <% end %>
  </table>


<% end %>
<% if current_user.try(:admin?) or current_user.try(:superadmin?) %>
  <p>
    <%= link_to 'Add Car', new_car_path, class: 'btn btn-primary' %>
    <%= link_to "Back", :back, class: 'btn btn-primary' %>
  </p>
<% end %>

app/views/cars/new.html.erb
<h1>Add a New Car</h1>
<%= render 'form' %>

app/views/cars/show.html.erb
<h1>Car: <%= @car.id %></h1>
<h3>Model: <%= @car.model %></h3>
<h3>Manufacturer: <%= @car.manufacturer %></h3>

<br />
<p>
  <%= link_to 'Edit', edit_car_path(@car) %>
</p>

<p>
  <%= link_to 'All Cars', cars_url %>
</p>

app/views/cars/update.html.erb
<h1>Cars#update</h1>
<p>Find me in app/views/cars/update.html.erb</p>